// GENERATED by scripts/build-previews.js — do not edit by hand.
// Recorded card previews, keyed by component id. Components missing here fall
// back to rendering live in the card.
const previews = {
  "ascii-particle-text": {
    "video": "/preview/ascii-particle-text.mp4",
    "poster": "/preview/ascii-particle-text.webp"
  },
  "curved-card-marquee": {
    "video": "/preview/curved-card-marquee.mp4",
    "poster": "/preview/curved-card-marquee.webp"
  },
  "curved-carousel": {
    "video": "/preview/curved-carousel.mp4",
    "poster": "/preview/curved-carousel.webp"
  },
  "image-queue": {
    "video": "/preview/image-queue.mp4",
    "poster": "/preview/image-queue.webp"
  },
  "paint-spread-wordmark": {
    "video": "/preview/paint-spread-wordmark.mp4",
    "poster": "/preview/paint-spread-wordmark.webp"
  },
  "scroll-assemble-image": {
    "video": "/preview/scroll-assemble-image.mp4",
    "poster": "/preview/scroll-assemble-image.webp"
  },
  "snap-deck": {
    "video": "/preview/snap-deck.mp4",
    "poster": "/preview/snap-deck.webp"
  },
  "sphere-album": {
    "video": "/preview/sphere-album.mp4",
    "poster": "/preview/sphere-album.webp"
  },
  "spherical-gallery": {
    "video": "/preview/spherical-gallery.mp4",
    "poster": "/preview/spherical-gallery.webp"
  },
  "tarot-carousel": {
    "video": "/preview/tarot-carousel.mp4",
    "poster": "/preview/tarot-carousel.webp"
  },
  "floating-arc-slider": {
    "video": "/preview/curved-card-marquee.mp4",
    "poster": "/preview/curved-card-marquee.webp"
  }
};

export default previews;

export function previewFor(id) {
  return previews[id] ?? null;
}
